apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\TSB\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: eureka-service
  name: eureka-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eureka-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\TSB\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: eureka-service
    spec:
      containers:
        - image: chauhoangtan/eureka-service:latest
          name: eureka-service
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
